#!/bin/sh

./gradlew build

docker build ./ --platform linux/amd64 --build-arg JAR_FILE=build/libs/SwapAdmin-1.0.0-SNAPSHOT.jar -t avera/swap-monitor:1.0.0_linux -f docker/build/Dockerfile

#docker save avera/swap-monitor:1.0.0_linux -o /tmp/Swap-monitor.1.0.0_linux.tar.gz

