#!/bin/sh

./gradlew build

docker build --platform linux/amd64 --build-arg JAR_FILE=build/libs/cnswapweb-1.0.0-SNAPSHOT.jar -t avera/cnswap:0.0.1_linux .

docker save avera/cnswap:0.0.1_linux -o /tmp/cnswap.0.0.1_linux.tar.gz

scp -i ~/.ssh/id_rsa /tmp/cnswap.0.0.1_linux.tar.gz angelvera@34.71.244.168:/tmp/cnswap.0.0.1_linux.tar.gz

echo "ssh -i ~/.ssh/id_rsa angelvera@34.71.244.168"

echo "sudo su - "

echo "docker stop swapy"

echo "docker image load -i /tmp/cnswap_0.0.1_linux.tar.gz"

echo "docker run -d --name swapy -p 80:8080 avera/cnswap:0.0.1_linux"