services:
  cnswap:
    image: "swapy_app:latest"
    ports:
      - "80:8080"
      - "443:443"
    restart: always
    environment:
      - TZ=America/Toronto
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_SQL_INIT_MODE=always
  db:
    image: "postgres:16.3-bookworm"
    restart: always
    environment:
      - POSTGRES_USER=cnswap
      - POSTGRES_PASSWORD=vvLv2ndnZ
      - POSTGRES_DB=cnswapdb
      - TZ=America/Toronto
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    expose:
      - 5432
volumes:
  db_data:
